application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      appbuilder-examples:
        license: Apache-2.0
        actions:
          state-in-memory:
            function: actions/handling-state/in-memory.js
            web: 'yes'
            runtime: 'nodejs:14'
            annotations:
              require-adobe-auth: false
              final: true
          aio-lib-state-counter:
            function: actions/handling-state/lib-state.js
            web: 'yes'
            runtime: 'nodejs:14'
            annotations:
              require-adobe-auth: false
              final: true
